image: python:3.11

stages:
  - lint
  - test

lint-flake8-test:
  stage: lint
  script:
    - pip install -r requirements.txt
    - flake8 ./api.py
    - isort --check-only .

tests:
  stage: test
  script:
    - chmod +x test.py
    - ./test.py