image: python:3.11

stages:
  - lint
  - test

lint-flake8-test:
  stage: lint
  script:
    - pip install -f requirements.txt
    - flake8 --ignore E501,W503,W605 --max-complexity 10 --max-line-length 120 --statistics
    - isort --check-only .

tests:
  stage: test
  script:
    - ./test.py

