version: '3.11'
services:
  redis:
    image: redis:7.2.1-alpine
    container_name: scoringapi
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass mwMtyKVge8oLd2t81
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local