name: Python package

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8/isort
      run: |
        flake8 . 
        isort --check-only .
    - name: Tests
      run: |
        python -m unittest discover -s ./tests/integration/  -p 'test_*.py'
        python -m unittest discover -s ./tests/unit/  -p 'test_*.py'